version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/hoverfly-java
    steps:
      - checkout
      - restore_cache:
          key: hoverfly-java-gradle-cache-
      - run:
          name: Run Tests
          command: ./gradlew clean test jacocoTestReport
      - store_artifacts:
          path: build/reports
          destination: reports
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: hoverfly-java-gradle-cache-{{ checksum "build.gradle" }}
      - run:
           name: Upload code coverage reports
           command: bash <(curl -s https://codecov.io/bash)